### ISSUE TITLE
Unable to read/get SVG icons for D365 (9.0)

### ISSUE THREAD

**Issue by AQ64** [MscrmTools/MscrmTools.Iconator#6]
When I click on an Entity that has .SVG icons it gives an error as below. Other entities with non-svg icons work fine.
Error: 
"See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Exception: Error on ConvertWebResContent method : Parameter is not valid.
   at MsCrmTools.Iconator.AppCode.ImageHelper.ConvertWebResContent(String contentImageList, Boolean isVector)
   at MsCrmTools.Iconator.Iconator.LvEntitiesSelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ListView.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2650.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll"

![image](https://user-images.githubusercontent.com/38721054/41230039-e9398b5e-6d9b-11e8-8d2f-11f2d9ef8655.png)

**Comment by MscrmTools** [comment]
Can you share one of your svg icon?

**Comment by AQ64** [comment]
Thanks for the quick reply.
Sure, I can share it. 
To confirm I have tried this in a Trial Org and used an OOB SVG icon present in Web Resources on a simple Test Entity.
Name - "msdyn_/Images/InAppCustomization_BasicSetup_Selected_Icon.svg".
Display Name - InAppCustomization_BasicSetup_Selected_Icon.svg

Also attached here,
[Selected_SVG.zip](https://github.com/MscrmTools/MscrmTools.Iconator/files/2089847/Selected_SVG.zip)
