### ISSUE TITLE
Exception Thrown when Selecting Entity

### ISSUE THREAD

**Issue by DaveStabilify** [MscrmTools/MscrmTools.Iconator#9]
Exception thrown when clicking on entity. Cannot continue.

https://user-images.githubusercontent.com/33522415/115460134-e373ab00-a1f5-11eb-9fa1-781e61b1a0b9.mp4

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Exception: Error on ConvertWebResContent method : Parameter is not valid.
   at MsCrmTools.Iconator.AppCode.ImageHelper.ConvertWebResContent(String contentImageList, Boolean isVector)
   at MsCrmTools.Iconator.Iconator.LvEntitiesSelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ListView.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by MscrmTools** [comment]
Thank you for reporting.
This one might be tricky to fix. Can you tell me if icon is already set for that entity? if so, can you send me the corresponding file?
